{% set version = '0.8.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-multiblock
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/multiblock_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/multiblock/multiblock_{{ version }}.tar.gz
  sha256: 2273f0ae3ffee57b5af7b58e4f3123f1854a72cc0c82849b2329b8eb0dec29f6

build:
  skip: true  # [win]
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - {{ cdt('mesa-libgl-devel') }}    # [linux]
    - {{ cdt('mesa-dri-drivers') }}    # [linux]
    - {{ cdt('libselinux') }}          # [linux]
    - {{ cdt('libxdamage') }}          # [linux]
    - {{ cdt('libxxf86vm') }}          # [linux]
    - {{ cdt('libxext') }}             # [linux]
  host:
    - xorg-libxfixes                   # [linux]
    - r-base
    - r-mass
    - r-rspectra
    - r-rcpp
    - r-rcppeigen
    - r-ssbtools
    - r-ade4
    - r-car
    - r-lme4
    - r-mixlm
    - r-plotrix
    - r-pls
    - r-plsvarsel
    - r-pracma
    - r-progress
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-rspectra
    - r-rcpp
    - r-rcppeigen
    - r-ssbtools
    - r-ade4
    - r-car
    - r-lme4
    - r-mixlm
    - r-plotrix
    - r-pls
    - r-plsvarsel
    - r-pracma
    - r-progress

test:
  commands:
    - $R -e "library('multiblock')"           # [not win]
    - "\"%R%\" -e \"library('multiblock')\""  # [win]

about:
  home: https://khliland.github.io/multiblock/, https://github.com/khliland/multiblock/
  license: GPL-2.0-or-later
  summary: "Functions and datasets to support Smilde, N\xE6s and Liland (2021, ISBN: 978-1-119-60096-1)
    \"Multiblock Data Fusion in Statistics and Machine Learning - Applications in the
    Natural and Life Sciences\". This implements and imports a large collection of methods
    for multiblock data analysis with common interfaces, result- and plotting functions,
    several real data sets and six vignettes covering a range different applications."
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
# Encoding: UTF-8

extra:
  recipe-maintainers:
    - conda-forge/r
    - RJMW

# Package: multiblock
# Type: Package
# Title: Multiblock Data Fusion in Statistics and Machine Learning
# Version: 0.8.6
# Date: 2023-06-04
# Authors@R: c(person(given = "Kristian Hovde", family = "Liland", role = c("aut", "cre"), email = "kristian.liland@nmbu.no", comment = c(ORCID = "0000-0001-6468-9423")), person(given = "Solve", family = "Sb", role = c("ctb")), person(given = "Stefan", family = "Schrunner", role = c("rev")))
# Description: Functions and datasets to support Smilde, Ns and Liland (2021, ISBN: 978-1-119-60096-1) "Multiblock Data Fusion in Statistics and Machine Learning - Applications in the Natural and Life Sciences". This implements and imports a large collection of methods for multiblock data analysis with common interfaces, result- and plotting functions, several real data sets and six vignettes covering a range different applications.
# License: GPL (>= 2)
# URL: https://khliland.github.io/multiblock/, https://github.com/khliland/multiblock/
# BugReports: https://github.com/khliland/multiblock/issues/
# Depends: R (>= 3.5.0)
# Imports: ade4, car, lme4, MASS, mixlm, plotrix, pls, plsVarSel, pracma, progress, Rcpp, RSpectra, SSBtools
# Suggests: FactoMineR, geigen, RegularizedSCA, RGCCA (>= 3.0.0), r.jive, rmarkdown, knitr
# LinkingTo: Rcpp, RcppEigen
# RoxygenNote: 7.2.3
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2023-06-04 20:00:05 UTC; kristian
# Author: Kristian Hovde Liland [aut, cre] (<https://orcid.org/0000-0001-6468-9423>), Solve Sb [ctb], Stefan Schrunner [rev]
# Maintainer: Kristian Hovde Liland <kristian.liland@nmbu.no>
# Repository: CRAN
# Date/Publication: 2023-06-04 20:20:02 UTC
