{% set version = "0.8.9.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-multiblock
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/multiblock_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/multiblock/multiblock_{{ version }}.tar.gz
  sha256: de5e86b2328879dc8fa694b0837ced5c543b6bacdc787d81b32d3608179de823

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - {{ cdt('mesa-libgl-devel') }}    # [linux]
    - {{ cdt('mesa-dri-drivers') }}    # [linux]
    - {{ cdt('libselinux') }}          # [linux]
    - {{ cdt('libxdamage') }}          # [linux]
    - {{ cdt('libxxf86vm') }}          # [linux]
    - {{ cdt('libxext') }}             # [linux]
  host:
    - xorg-libxfixes                   # [linux]
    - r-base
    - r-hdanova
    - r-mass
    - r-rspectra
    - r-rcpp
    - r-rcppeigen
    - r-ssbtools
    - r-ade4
    - r-car
    - r-mixlm
    - r-plotrix
    - r-pls
    - r-plsvarsel
    - r-pracma
    - r-progress
  run:
    - r-base
    - r-hdanova
    - r-mass
    - r-rspectra
    - r-rcpp
    - r-rcppeigen
    - r-ssbtools
    - r-ade4
    - r-car
    - r-mixlm
    - r-plotrix
    - r-pls
    - r-plsvarsel
    - r-pracma
    - r-progress

test:
  commands:
    - $R -e "library('multiblock')"           # [not win]
    - "\"%R%\" -e \"library('multiblock')\""  # [win]

about:
  home: https://khliland.github.io/multiblock/
  dev_url: https://github.com/khliland/multiblock/
  license: GPL-2.0-or-later
  summary: "Functions and datasets to support Smilde, Næs and Liland (2021, ISBN: 978-1-119-60096-1) \"Multiblock Data Fusion in Statistics and Machine Learning - Applications in the Natural and Life Sciences\". This implements and imports a large collection of methods for multiblock data analysis with common interfaces,
    result- and plotting functions, several real data sets and six vignettes covering a range different applications."
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - RJMW
